// <auto-generated />
using System;
using Api.TpFinanceiro.Data.Contextes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.TpFinanceiro.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.TpFinanceiro.Data.Entities.Financias", b =>
                {
                    b.Property<Guid?>("IdFinancias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFINANCIAS");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATA");

                    b.Property<Guid?>("IdTpFinancias")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDTPFINANCIAS");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("META");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("OBS");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdFinancias");

                    b.HasIndex("IdTpFinancias");

                    b.ToTable("FINACIAS", (string)null);
                });

            modelBuilder.Entity("Api.TpFinanceiro.Data.Entities.TpFinancias", b =>
                {
                    b.Property<Guid?>("IdTPFinancias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDFINANCIAS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.HasKey("IdTPFinancias");

                    b.ToTable("TPFINANCEIRO", (string)null);
                });

            modelBuilder.Entity("Api.TpFinanceiro.Data.Entities.Financias", b =>
                {
                    b.HasOne("Api.TpFinanceiro.Data.Entities.TpFinancias", "Tpfinancias")
                        .WithMany("Financias")
                        .HasForeignKey("IdTpFinancias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tpfinancias");
                });

            modelBuilder.Entity("Api.TpFinanceiro.Data.Entities.TpFinancias", b =>
                {
                    b.Navigation("Financias");
                });
#pragma warning restore 612, 618
        }
    }
}
